- name: initiate reverse ssh tunnel
  hosts: localhost
  #error on any host will stop all
  any_errors_fatal: true
  gather_facts: no
  vars_files:
    - vars.yml
  
      # vars_prompt:
      # - name: vault_token
      #   prompt: Enter the vault token

  roles:
    - create_tunnel
#    - destroy_tunnel
