- name: create tunnel
  # shell: ' ssh -i {{ key_location }} -fN -R {{ target_port }}:localhost:22 {{ target_user }}@{{ target_host }}  & '
  shell: ' ssh -fN -R {{ target_port }}:localhost:22 {{ target_user }}@{{ target_host }}  & '
  delegate_to: 127.0.0.1  #run as local
